arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - only_ezgripper_knuckle_1
    - only_ezgripper_knuckle_2
    - only_ezgripper_knuckle_3
    - only_ezgripper_knuckle_4
